#!/usr/bin/env node
/* ============================================================
   build.js — generates js/config.js from environment variables.
   Runs locally (reads a .env file) and on Vercel (reads the
   dashboard Environment Variables). No dependencies.

   Local:   node build.js        (reads .env)
   Vercel:  set as the Build Command; env vars come from the project.

   Reads:  SUPABASE_URL, SUPABASE_ANON_KEY
   Writes: js/config.js  (git-ignored — never committed)
   If a value is missing, a placeholder is written so the app still
   runs in guest mode instead of breaking the build.
   ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');

// --- read .env (if present) into an object; simple KEY=VALUE parser ---
function readEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  fs.readFileSync(file, 'utf8').split(/\r?\n/).forEach((line) => {
    const s = line.trim();
    if (!s || s.startsWith('#')) return;
    const eq = s.indexOf('=');
    if (eq === -1) return;
    const key = s.slice(0, eq).trim();
    let val = s.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  });
  return out;
}

const fileEnv = readEnvFile(path.join(__dirname, '.env'));
// process.env (Vercel) wins over the local .env file.
function get(key) { return process.env[key] || fileEnv[key] || ''; }

const url = get('SUPABASE_URL') || 'YOUR_SUPABASE_URL';
const anonKey = get('SUPABASE_ANON_KEY') || 'YOUR_SUPABASE_ANON_KEY';

const configured = url !== 'YOUR_SUPABASE_URL' && anonKey !== 'YOUR_SUPABASE_ANON_KEY';

const contents =
`/* AUTO-GENERATED by build.js — do not edit by hand.
   Values come from environment variables (.env locally, Vercel env vars on deploy).
   The anon key is public by design; your data is protected by Supabase Row Level Security. */
window.SUPABASE_CONFIG = {
  url: ${JSON.stringify(url)},
  anonKey: ${JSON.stringify(anonKey)}
};
`;

const outPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(outPath, contents);

if (configured) {
  console.log('[build] Wrote js/config.js with Supabase config for ' + url);
} else {
  console.warn('[build] SUPABASE_URL / SUPABASE_ANON_KEY not set — wrote guest-mode placeholders to js/config.js.');
  console.warn('[build] (App still works without login. Set the env vars to enable accounts.)');
}
