/* AUTO-GENERATED by gen-audio.js — lists which words have a pre-recorded
   MP3 in this folder. Until you run gen-audio.js this is empty and the app
   falls back to the device's built-in text-to-speech voice. */
window.AUDIO_MANIFEST = {};
